### ISSUE TITLE
Running it on Linux

### ISSUE THREAD

**Issue by Hawkansson86** [simos421/CST-MATLAB-API#6]
Hi, it seems like the actxserver command in matlab is exclusive to Windows environment only. Are there any ways to get the same functionality in another operating system (I tried the Microstrip example in Linux), or is this simply outside the scope for this API? Best regards, David

**Comment by simos421** [comment]
Hi, this is a very interesting question. It is always welcome to expand the
capabilities of the API to other operating systems. I did it on windows
because it's the most commonly used OS for CST + Matlab applications. Doing
this in Linux will require additional Matlab and CST licences for linux.
This means that it will be way beyond my budget at the moment. I think that
if you have the licence it won't need but a bit of tweaking here and there
and then the code will play fine in linux.

Thanks
Simos

**Comment by Hawkansson86** [comment]
Thanks for the quick answer! I will investigate this and see if there is a work-around, since COM servers do not seem to be possible to use outside Windows.
